# Generated by Django 4.1.2 on 2022-11-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('china', '0047_order_archive_order_ready_order_real_in_moscow_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('cargo_number', models.CharField(max_length=264, verbose_name='Номер карго')),
                ('cargo_volume', models.CharField(blank=True, max_length=256, null=True, verbose_name='Объем карго')),
                ('cargo_weight', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вес карго')),
                ('arrived_in_moscow', models.DateField(blank=True, null=True, verbose_name='Дата приезда в Москву')),
                ('shipped_from_china', models.DateField(blank=True, null=True, verbose_name='Дата отправки из Китая')),
                ('custom_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(blank=True, to='china.productquantity')),
            ],
            options={
                'verbose_name': 'Приемка',
                'verbose_name_plural': 'Приемки',
            },
        ),
    ]
