# Generated by Django 4.1.2 on 2022-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0002_remove_acceptance_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
