# Generated by Django 4.1.2 on 2022-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0003_acceptance_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264, unique=True, verbose_name='Юзер')),
                ('password', models.CharField(max_length=264, verbose_name='Пароль')),
                ('inactive', models.BooleanField(default=False, verbose_name='Деактивирован')),
                ('temporary', models.BooleanField(default=False, verbose_name='Временный')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
