# Generated by Django 4.1.2 on 2022-11-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('acceptance', '0004_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул поставщика')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер')),
                ('brand', models.CharField(max_length=100, verbose_name='Брэнд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.acceptancecategory', verbose_name='Категория')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptance_photo_product', to='documents.photo', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
