# Generated by Django 4.1.2 on 2022-11-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0006_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceptance.product', verbose_name='Товар')),
            ],
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='products',
            field=models.ManyToManyField(blank=True, to='acceptance.productspecification'),
        ),
    ]
