# Generated by Django 4.1.2 on 2022-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0011_product_barcode_product_total_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=24, verbose_name='Номер Коробки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во товаров в коробке')),
            ],
            options={
                'verbose_name': 'Коробка',
                'verbose_name_plural': 'Коробки',
            },
        ),
        migrations.AddField(
            model_name='productspecification',
            name='boxes',
            field=models.ManyToManyField(blank=True, to='acceptance.box', verbose_name='Коробки'),
        ),
    ]
