# Generated by Django 4.1.2 on 2022-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0012_box_productspecification_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='actual_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Фактическое Количество Товаров'),
        ),
    ]
