# Generated by Django 4.1.2 on 2022-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0019_alter_acceptance_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
            },
        ),
        migrations.AddField(
            model_name='productspecification',
            name='reasons',
            field=models.ManyToManyField(blank=True, to='acceptance.reason', verbose_name='Причины'),
        ),
    ]
