# Generated by Django 4.1.2 on 2022-11-29 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0021_acceptance_comment_acceptance_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('color', models.CharField(help_text='Цвет на фронте', max_length=40, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
