# Generated by Django 4.1.2 on 2022-11-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0022_acceptancestatus_alter_acceptance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='status',
            field=models.ForeignKey(default='Новая Приемка', on_delete=django.db.models.deletion.PROTECT, to='acceptance.acceptancestatus', to_field='status', verbose_name='Статус'),
        ),
    ]
