# Generated by Django 4.1.2 on 2022-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0023_acceptance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='unique_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Уникальный Номер'),
        ),
    ]
