# Generated by Django 4.1.2 on 2022-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0024_staffmember_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='unique_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Уникальный Номер'),
        ),
    ]
