# Generated by Django 4.1.2 on 2022-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0025_alter_staffmember_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box',
            field=models.CharField(max_length=24, verbose_name='Номер Коробки'),
        ),
    ]
