# Generated by Django 4.1.2 on 2022-12-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0026_alter_box_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancecategory',
            name='payment',
            field=models.CharField(blank=True, choices=[('hourly', 'Почасовая'), ('apiece', 'Поштучно')], max_length=64, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='acceptancecategory',
            name='per_hour',
            field=models.FloatField(blank=True, null=True, verbose_name='За час'),
        ),
        migrations.AddField(
            model_name='acceptancecategory',
            name='per_piece',
            field=models.FloatField(blank=True, null=True, verbose_name='За штуку'),
        ),
    ]
