# Generated by Django 4.1.2 on 2022-12-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0027_acceptancecategory_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_for_box', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.product', verbose_name='Текущий Товар'),
        ),
        migrations.AddField(
            model_name='box',
            name='worker',
            field=models.ForeignKey(blank=True, db_column='worker_for_box', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.staffmember', verbose_name='Текущий Работник'),
        ),
    ]
