# Generated by Django 4.1.2 on 2022-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0028_box_product_box_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='product',
        ),
        migrations.RemoveField(
            model_name='box',
            name='worker',
        ),
    ]
