# Generated by Django 4.1.2 on 2022-12-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0031_box_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='worker',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.box', verbose_name='Коробка'),
        ),
    ]
