# Generated by Django 4.1.2 on 2022-12-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0032_remove_box_worker_staffmember_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='product',
        ),
        migrations.AddField(
            model_name='box',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.productspecification', verbose_name='Информация О Товаре'),
        ),
    ]
