# Generated by Django 4.1.2 on 2022-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0033_remove_box_product_box_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архивная Коробка'),
        ),
    ]
