# Generated by Django 4.1.2 on 2022-12-04 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0034_box_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время Начала')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Время Конца')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во упакованных')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
    ]
