# Generated by Django 4.1.2 on 2022-12-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0035_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.session', verbose_name='Сессия'),
        ),
    ]
