# Generated by Django 4.1.2 on 2022-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0036_staffmember_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Закончена'),
        ),
    ]
