# Generated by Django 4.1.2 on 2022-12-07 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0038_rename_session_worksession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время Начала')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Время Конца')),
                ('break_start', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время Начала Перерыва')),
                ('break_end', models.DateTimeField(blank=True, null=True, verbose_name='Время Конца Перерыва')),
            ],
            options={
                'verbose_name': 'Сессия По Времени',
                'verbose_name_plural': 'Сессии По Времени',
            },
        ),
        migrations.AlterModelOptions(
            name='worksession',
            options={'verbose_name': 'Рабочая Сессия', 'verbose_name_plural': 'Рабочая Сессии'},
        ),
        migrations.AddField(
            model_name='staffmember',
            name='time_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='acceptance.worksession', verbose_name='Сессия По Времени'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='acceptance.worksession', verbose_name='Сессия По Коробкам'),
        ),
    ]
