# Generated by Django 4.1.2 on 2022-12-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0039_timesession_alter_worksession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='time_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='acceptance.timesession', verbose_name='Сессия По Времени'),
        ),
    ]
