# Generated by Django 4.1.2 on 2022-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0040_alter_staffmember_time_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesession',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время Начала Перерыва'),
        ),
    ]
