# Generated by Django 4.1.2 on 2022-12-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_individualentrepreneur_project'),
        ('acceptance', '0043_alter_acceptance_cargo_number_alter_acceptance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.individualentrepreneur', verbose_name='ИП'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.project', verbose_name='Проект'),
        ),
    ]
