# Generated by Django 4.1.2 on 2022-12-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0044_acceptance_individual_acceptance_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='quantity',
        ),
        migrations.AddField(
            model_name='worksession',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceptance.box', verbose_name='Коробка'),
            preserve_default=False,
        ),
    ]
