# Generated by Django 4.1.2 on 2022-12-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0047_alter_worksession_legit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='legit',
        ),
    ]
