# Generated by Django 4.1.2 on 2022-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0049_worksession_legit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_break', models.PositiveSmallIntegerField(default=0, help_text='В минутах', verbose_name='Оплачиваемый Перерыв')),
                ('hour_cost', models.PositiveSmallIntegerField(default=0, help_text='В рублях', verbose_name='Стоимость Одного Часа Сотрудника')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
    ]
