# Generated by Django 4.1.2 on 2022-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0050_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Закончен На Сегодня'),
        ),
    ]
