# Generated by Django 4.1.2 on 2022-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0051_staffmember_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wb_article',
        ),
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Этикетка ПДФ'),
        ),
    ]
