# Generated by Django 4.1.2 on 2022-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название товара')),
                ('url', models.URLField(verbose_name='Ссылка на товар')),
                ('photo_url', models.URLField(verbose_name='Ссылка на фото товара')),
                ('nm', models.CharField(max_length=64, unique=True, verbose_name='Номер товара')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
    ]
