# Generated by Django 4.1.2 on 2022-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftOverDetailedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='leftover',
            name='nm',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Номер товара'),
        ),
        migrations.AlterField(
            model_name='leftover',
            name='title',
            field=models.CharField(editable=False, max_length=256, unique=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='leftover',
            name='detailed_data',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to='leftover.leftoverdetaileddata', verbose_name='Детальные данные'),
        ),
    ]
