# Generated by Django 4.1.2 on 2022-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0002_leftoverdetaileddata_alter_leftover_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftover',
            name='detailed_data',
            field=models.ManyToManyField(blank=True, null=True, to='leftover.leftoverdetaileddata', verbose_name='Детальные данные'),
        ),
    ]
