# Generated by Django 4.1.2 on 2022-10-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0005_alter_leftover_detailed_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leftover',
            old_name='detailed_data',
            new_name='products',
        ),
    ]
