# Generated by Django 4.1.2 on 2022-10-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0006_rename_detailed_data_leftover_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftover',
            name='title',
            field=models.CharField(editable=False, max_length=256, verbose_name='Название товара'),
        ),
    ]
