# Generated by Django 4.1.2 on 2022-11-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0007_alter_leftover_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего товара'),
        ),
    ]
