# Generated by Django 4.1.2 on 2022-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0008_leftover_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover',
            name='buffer',
            field=models.ManyToManyField(blank=True, editable=False, related_name='buffer_leftovers', to='leftover.leftoverdetaileddata', verbose_name='Прошлые остатки'),
        ),
        migrations.AlterField(
            model_name='leftover',
            name='products',
            field=models.ManyToManyField(blank=True, editable=False, to='leftover.leftoverdetaileddata', verbose_name='Остатки'),
        ),
    ]
