# Generated by Django 4.1.2 on 2022-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftover', '0009_leftover_buffer_alter_leftover_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover',
            name='buffer_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Было в начале дня'),
        ),
    ]
