# Generated by Django 4.1.2 on 2022-12-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_entrepreneur', models.CharField(max_length=80, unique=True, verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=80, unique=True, verbose_name='Заказ под проект')),
            ],
            options={
                'verbose_name': 'Заказ под проект',
                'verbose_name_plural': 'Заказы под проекты',
            },
        ),
    ]
