# Generated by Django 4.1.2 on 2022-10-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('china_distributor', models.CharField(max_length=80, unique=True, verbose_name='Китайский посредник')),
            ],
            options={
                'verbose_name': 'Китайский посредник',
                'verbose_name_plural': 'Китайские посредники',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_entrepreneur', models.CharField(max_length=80, unique=True, verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='OrderForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_for_project', models.CharField(max_length=80, unique=True, verbose_name='Заказ под проект')),
            ],
            options={
                'verbose_name': 'Заказ под проект',
                'verbose_name_plural': 'Заказы под проекты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название товара')),
                ('price_cny', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена в юанях')),
                ('cny_to_rub_course', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Курс юаня к рублю')),
                ('price_rub', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('commentary', models.TextField(verbose_name='Комментарий')),
                ('china_distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='china.chinadistributor', verbose_name='Китайский посредник')),
                ('individual_entrepreneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='china.individualentrepreneur', verbose_name='Индивидуальный предприниматель')),
                ('order_for_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='china.orderforproject', verbose_name='Заказ под проект')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='china.status', verbose_name='Статус')),
            ],
        ),
    ]
