# Generated by Django 4.1.2 on 2022-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0002_alter_order_options_alter_order_china_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
