# Generated by Django 4.1.2 on 2022-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0003_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='china.product', verbose_name='Товары'),
        ),
    ]
