# Generated by Django 4.1.2 on 2022-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0004_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
