# Generated by Django 4.1.2 on 2022-10-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0005_product_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='china.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт/кол-во',
                'verbose_name_plural': 'Продукты/кол-ва',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='china.productquantity', verbose_name='Товары'),
        ),
    ]
