# Generated by Django 4.1.2 on 2022-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
