# Generated by Django 4.1.2 on 2022-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0010_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
