# Generated by Django 4.1.2 on 2022-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0012_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='123', help_text='Цвет в jsx формате', max_length=40, verbose_name='Цвет'),
        ),
    ]
