# Generated by Django 4.1.2 on 2022-10-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0013_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(help_text='Цвет в jsx формате', max_length=40, verbose_name='Цвет'),
        ),
    ]
