# Generated by Django 4.1.2 on 2022-10-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0014_alter_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
    ]
