# Generated by Django 4.1.2 on 2022-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0017_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_id',
            field=models.CharField(default=1, editable=False, max_length=10, verbose_name='Кастомное айди'),
            preserve_default=False,
        ),
    ]
