# Generated by Django 4.1.2 on 2022-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0018_order_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hover_color',
            field=models.CharField(default=1, help_text='Цвет в jsx формате', max_length=40, verbose_name='Цвет при наведении на блок'),
            preserve_default=False,
        ),
    ]
