# Generated by Django 4.1.2 on 2022-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0019_status_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
