# Generated by Django 4.1.2 on 2022-10-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0020_status_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='icon',
            new_name='photo',
        ),
    ]
