# Generated by Django 4.1.2 on 2022-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0023_order_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cny_to_rub_course',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cny',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_rub',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='cny_to_rub_course',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Курс юаня к рублю'),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='price_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена в юанях'),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена в рублях'),
        ),
    ]
