# Generated by Django 4.1.2 on 2022-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0024_remove_product_cny_to_rub_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='additional_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доп. расходы в рублях'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='cny_to_rub_course',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Курс юаня к рублю'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='price_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена в юанях'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена в рублях'),
        ),
    ]
