# Generated by Django 4.1.2 on 2022-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0025_productquantity_additional_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма в юанях'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доп. расходы в рублях'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма в юанях'),
        ),
    ]
