# Generated by Django 4.1.2 on 2022-10-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0026_order_total_cny_order_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_date',
            field=models.DateField(blank=True, null=True, verbose_name='Время изготовления'),
        ),
    ]
