# Generated by Django 4.1.2 on 2022-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0027_order_ready_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер Доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='cargo_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем карго'),
        ),
        migrations.AddField(
            model_name='order',
            name='cargo_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес карго'),
        ),
        migrations.AddField(
            model_name='order',
            name='package_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена упаковки, $'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_per_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за кг, $'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_delivery',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за доствку, $'),
        ),
    ]
