# Generated by Django 4.1.2 on 2022-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0028_order_cargo_number_order_cargo_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_moscow_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приезда в Москву'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_from_china_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки из китая'),
        ),
    ]
