# Generated by Django 4.1.2 on 2022-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0030_alter_order_cargo_number_alter_order_cargo_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Курс'),
        ),
    ]
