# Generated by Django 4.1.2 on 2022-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0031_order_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Доставлен'),
        ),
    ]
