# Generated by Django 4.1.2 on 2022-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0033_product_brand_product_color_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка на товар'),
            preserve_default=False,
        ),
    ]
