# Generated by Django 4.1.2 on 2022-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0036_order_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
