# Generated by Django 4.1.2 on 2022-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0039_remove_order_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='documents/auto/', verbose_name='Эксель'),
        ),
    ]
