# Generated by Django 4.1.2 on 2022-11-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0040_order_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
