# Generated by Django 4.1.2 on 2022-11-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('china', '0042_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.document', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.photo', verbose_name='Картинка'),
        ),
    ]
