# Generated by Django 4.1.2 on 2022-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0044_alter_order_course_alter_order_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expenses_rub',
            field=models.FloatField(default=0, verbose_name='Курс'),
        ),
    ]
