# Generated by Django 4.1.2 on 2022-11-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0046_order_expenses_cny'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Товар Изготовлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='real_in_moscow_date',
            field=models.DateField(blank=True, null=True, verbose_name='Реальная Дата приезда в Москву'),
        ),
        migrations.AlterField(
            model_name='order',
            name='china_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='china.chinadistributor', verbose_name='Китайский посредник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expenses_cny',
            field=models.FloatField(default=0, verbose_name='Затраты, юаней'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expenses_rub',
            field=models.FloatField(default=0, verbose_name='Затраты, рублей'),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_moscow_date',
            field=models.DateField(blank=True, null=True, verbose_name='Примерная Дата приезда в Москву'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='china.orderforproject', verbose_name='Заказ под проект'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_rub',
            field=models.FloatField(default=0, verbose_name='Сумма в рублях'),
        ),
    ]
