# Generated by Django 4.1.2 on 2022-11-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0047_order_archive_order_ready_order_real_in_moscow_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='archive',
        ),
    ]
