# Generated by Django 4.1.2 on 2022-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0048_remove_order_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
