# Generated by Django 4.1.2 on 2022-11-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0003_acceptance_custom_id'),
        ('china', '0049_order_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acceptance.acceptance', verbose_name='Приемка'),
        ),
    ]
