# Generated by Django 4.1.2 on 2022-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0052_rename_productquantity_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_expenses',
            field=models.FloatField(default=0, verbose_name='Фактическая цена за доставку, $'),
        ),
        migrations.AddField(
            model_name='order',
            name='dollar_to_rub',
            field=models.FloatField(default=0, verbose_name='Курс, $ к ₽'),
        ),
        migrations.AddField(
            model_name='order',
            name='real_total_delivery',
            field=models.FloatField(default=0, verbose_name='Фактическая цена за доставку, $'),
        ),
    ]
