# Generated by Django 4.1.2 on 2022-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('china', '0053_order_delivery_expenses_order_dollar_to_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_expenses',
            field=models.FloatField(default=0, verbose_name='Доп. затраты за доставку, ₽'),
        ),
    ]
