# Generated by Django 4.1.2 on 2022-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('china', '0054_alter_order_delivery_expenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='order',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='common.task', verbose_name='Задачи'),
        ),
    ]
