# Generated by Django 4.1.2 on 2022-12-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_individualentrepreneur_project'),
        ('china', '0055_delete_task_alter_order_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='individual_entrepreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.individualentrepreneur', verbose_name='Индивидуальный предприниматель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.project', verbose_name='Заказ под проект'),
        ),
        migrations.DeleteModel(
            name='IndividualEntrepreneur',
        ),
        migrations.DeleteModel(
            name='OrderForProject',
        ),
    ]
